# Generated by Django 5.0.2 on 2024-02-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_patient_detailes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_appointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient_appointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient_appointment',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patient_appointment',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient_appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient_appointment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient_appointment',
            name='illnesses',
        ),
        migrations.RemoveField(
            model_name='patient_appointment',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='patient_appointment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='patient_appointment',
            name='patient_detailes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.patient_detailes'),
        ),
    ]
