# Generated by Django 5.0.2 on 2024-02-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_patient_appointment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_detailes',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
