# Generated by Django 5.0.2 on 2024-02-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_patient_detailes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30, null=True),
        ),
    ]
