# Generated by Django 5.0.2 on 2024-02-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_patient_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_shop',
            fields=[
                ('tablet_id', models.AutoField(primary_key=True, serialize=False)),
                ('tablet_name', models.CharField(max_length=90)),
                ('company', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
