# Generated by Django 5.0.2 on 2024-02-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_doctor_prescription_adviced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_distribution',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.doctor_prescription'),
        ),
        migrations.AlterField(
            model_name='medicine_distribution',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
